import matplotlib
matplotlib.use('Agg') # Ensures backend rendering without GUI popups
import matplotlib.pyplot as plt
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor, Inches
from docx.enum.table import WD_ALIGN_VERTICAL
import datetime
import io

# --- HELPER FUNCTION: DRAW GAUGES FOR MS WORD ---
def create_gauge_image(score):
    color = "#ef4444" if score < 50 else "#f59e0b" if score < 90 else "#10b981"
    
    fig, ax = plt.subplots(figsize=(1.5, 1.5))
    # Create donut chart
    ax.pie([score, max(100-score, 0)], colors=[color, '#f1f5f9'], startangle=90, counterclock=False, wedgeprops=dict(width=0.25))
    # Add score text in center
    ax.text(0, 0, str(score), ha='center', va='center', fontsize=20, fontweight='bold', color='#0f172a', family='sans-serif')
    
    img_stream = io.BytesIO()
    plt.savefig(img_stream, format='png', transparent=True, bbox_inches='tight', dpi=150)
    plt.close(fig)
    img_stream.seek(0)
    return img_stream

def generate_word_report(url, onpage_data, speed_data, ai_suggestions):
    doc = Document()

    # --- BRANDING ---
    section = doc.sections[0]
    header = section.header
    header.paragraphs[0].text = "NexGenWebLab - Enterprise SEO Audit"
    header.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
    
    footer = section.footer
    footer.paragraphs[0].text = "Report generated by NexGenWebLab.com | Technical SEO Infrastructure"
    footer.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

    # --- PAGE 1: COVER ---
    doc.add_paragraph('\n\n\n')
    title = doc.add_heading('Website Audit Report', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    domain_name = url.replace('https://', '').replace('http://', '').strip('/')
    subtitle = doc.add_heading(domain_name.upper(), level=1)
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph('\n\n')
    
    table = doc.add_table(rows=4, cols=2)
    table.style = 'Table Grid'
    table.rows[0].cells[0].text = "Audit Date:"
    table.rows[0].cells[1].text = datetime.datetime.now().strftime("%d-%b-%Y")
    table.rows[1].cells[0].text = "Website URL:"
    table.rows[1].cells[1].text = url
    table.rows[2].cells[0].text = "Audited By:"
    table.rows[2].cells[1].text = "NexGenWebLab AI System"
    table.rows[3].cells[0].text = "Status:"
    table.rows[3].cells[1].text = "Completed"

    doc.add_page_break()

    # --- HELPER: TEXT DASHBOARD METRICS ---
    def add_metric(doc, label, value, condition):
        p = doc.add_paragraph()
        run_status = p.add_run(f"[{condition}] ")
        run_status.bold = True
        if condition == "FAIL": run_status.font.color.rgb = RGBColor(239, 68, 68)
        elif condition == "WARN": run_status.font.color.rgb = RGBColor(245, 158, 11)
        else: run_status.font.color.rgb = RGBColor(16, 185, 129)
        
        p.add_run(f"{label}: ").bold = True
        p.add_run(str(value))

    # --- PAGE 2: ON-PAGE ANALYTICS ---
    doc.add_heading('1. Technical SEO Analytics', level=1)
    doc.add_paragraph("The following is a direct snapshot of your website's technical architecture and SEO configuration.")
    
    doc.add_heading('Basic SEO Factors', level=2)
    add_metric(doc, "Title Tag", f"{onpage_data['title']} ({onpage_data['title_count']} chars)", "FAIL" if "Missing" in onpage_data['title'] else "PASS")
    add_metric(doc, "Meta Description", onpage_data['description'][:80]+"...", "FAIL" if "Missing" in onpage_data['description'] else "PASS")
    add_metric(doc, "H1 Heading", onpage_data['h1'][0] if isinstance(onpage_data['h1'], list) else onpage_data['h1'], "FAIL" if "Missing" in onpage_data['h1'] else "PASS")
    add_metric(doc, "Word Count", f"{onpage_data['word_count']} words", "WARN" if onpage_data['word_count'] < 300 else "PASS")
    add_metric(doc, "Images (ALT)", f"{onpage_data['missing_alt']} images missing ALT attributes", "WARN" if onpage_data['missing_alt'] > 0 else "PASS")
    
    doc.add_heading('Advanced SEO Factors', level=2)
    add_metric(doc, "Canonical URL", onpage_data['canonical'], "FAIL" if "Missing" in onpage_data['canonical'] else "PASS")
    add_metric(doc, "Meta Robots", onpage_data['meta_robots'], "PASS")
    add_metric(doc, "Noindex Tag", "Present (Search engines blocked)" if onpage_data['has_noindex'] == "Yes" else "Not found (Indexable)", "WARN" if onpage_data['has_noindex'] == "Yes" else "PASS")
    add_metric(doc, "Schema Markup", onpage_data['schema'], "FAIL" if onpage_data['schema'] == "Missing" else "PASS")
    
    doc.add_heading('Performance & Security', level=2)
    add_metric(doc, "Server Response Time", f"{onpage_data['response_time']} seconds", "WARN" if onpage_data['response_time'] > 0.5 else "PASS")
    add_metric(doc, "HTML Document Size", f"{onpage_data['html_size_kb']} KB", "WARN" if onpage_data['html_size_kb'] > 100 else "PASS")
    add_metric(doc, "HTTPS Protocol", "Secured" if onpage_data['is_https'] == "Yes" else "Unsecured", "FAIL" if onpage_data['is_https'] == "No" else "PASS")
    add_metric(doc, "Directory Listing", "Secured" if onpage_data['dir_listing_secured'] == "Yes" else "Exposed", "FAIL" if onpage_data['dir_listing_secured'] == "No" else "PASS")

    doc.add_page_break()

    # --- PAGE 3: VISUAL SPEED VITALS ---
    doc.add_heading('2. Core Web Vitals Snapshot', level=1)
    doc.add_paragraph("Lighthouse performance metrics simulating real-world browser rendering. Visual scores represent the overall health of your mobile and desktop interfaces.")
    
    def render_speed_section(platform_name, speed_obj):
        doc.add_heading(f'{platform_name} Vitals:', level=2)
        
        # Insert 4 Gauges in a Table
        table = doc.add_table(rows=2, cols=4)
        table.alignment = WD_ALIGN_VERTICAL.CENTER
        
        metrics = [
            ("Performance", speed_obj.get('performance', 0)),
            ("Accessibility", speed_obj.get('accessibility', 0)),
            ("Best Practices", speed_obj.get('best-practices', 0)),
            ("SEO", speed_obj.get('seo', 0))
        ]
        
        for i, (title, score) in enumerate(metrics):
            # Row 0: Images
            cell_img = table.cell(0, i)
            p_img = cell_img.paragraphs[0]
            p_img.alignment = WD_ALIGN_PARAGRAPH.CENTER
            p_img.add_run().add_picture(create_gauge_image(score), width=Inches(1.2))
            
            # Row 1: Titles
            cell_title = table.cell(1, i)
            p_title = cell_title.paragraphs[0]
            p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
            p_title.add_run(title).bold = True

        doc.add_paragraph("\nDetailed Metrics:")
        raw_metrics = speed_obj.get('metrics', {})
        doc.add_paragraph(f"First Contentful Paint (FCP): {raw_metrics.get('fcp', {}).get('value', 'N/A')}", style='List Bullet')
        doc.add_paragraph(f"Largest Contentful Paint (LCP): {raw_metrics.get('lcp', {}).get('value', 'N/A')}", style='List Bullet')
        doc.add_paragraph(f"Total Blocking Time (TBT): {raw_metrics.get('tbt', {}).get('value', 'N/A')}", style='List Bullet')
        doc.add_paragraph(f"Cumulative Layout Shift (CLS): {raw_metrics.get('cls', {}).get('value', 'N/A')}", style='List Bullet')
        doc.add_paragraph(f"Speed Index: {raw_metrics.get('si', {}).get('value', 'N/A')}", style='List Bullet')
        doc.add_paragraph("\n")

    render_speed_section('Mobile', speed_data['mobile'])
    render_speed_section('Desktop', speed_data['desktop'])

    doc.add_page_break()

    # --- PAGE 4: AI OVERVIEW ---
    doc.add_heading('3. AI Overview & Action Plan', level=1)
    doc.add_paragraph("Based on the technical snapshot above, our AI Engine has compiled the following strategic roadmap to resolve these issues systematically.")
    
    if ai_suggestions and isinstance(ai_suggestions, list):
        for item in ai_suggestions:
            p = doc.add_paragraph(style='List Bullet')
            p.add_run(f"{item.get('title', 'Recommendation')}: ").bold = True
            p.add_run(item.get('text', ''))
    else:
        doc.add_paragraph("Action plan data is currently unavailable.")

    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream